name: Build and Push Docker image to AWS ECR

inputs:
  repo:
    description: 'Repository name'
    required: true
  tag:
    description: 'Image tag'
    required: true
  dockerfile:
    description: 'Dockerfile to use'
    required: true
  extra-build-args:
    description: 'Extra arguments passed to `docker build`'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.tag }}
    - ${{ inputs.dockerfile }}
    - "${{ inputs.extra-build-args}}"
