name: Build and Push Docker image to AWS ECR

inputs:
  repo:
    description: 'Repository name'
    required: true
  tag:
    description: 'Image tag'
    required: true
  dockerfile:
    description: 'Dockerfile to use'
    required: true
  extra-build-args:
    description: 'Extra arguments passed to `docker build`'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        ./push_to_ecr.sh $REGISTRY ${{ inputs.repo }} ${{ inputs.tag }} ${{ inputs.dockerfile }} "${{ inputs.extra-build-args }}"
      shell: bash
